name: SimpleCI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lintTest:
    name: Apply Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          echo "Running Installing Dependencies"
          npm install

      - name: Run Linting
        run: |
          echo "Running Linting"
          npm run lint
          # you need this so that your does not run in watch mode.
        env:
          CI: true

  securityCheck:
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Check for Security
        runs: |
          echo "Running Security Check.."
          sleep 5s;
          echo "Security check 1...."
          sleep 5s;
          echo "Security check 2...."
          sleep 5s;
          echo "Security check 3...."
          sleep 5s;
          echo "Security check 4...."
          sleep 5s;

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [lintTest, securityCheck]
    steps:
      - name: Install Dependencies
        run: |
          echo "Deployement in Progress"
          sleep 5s;
